### ISSUE TITLE
[Scheduled Maintenance] Minecraft server down for Maintenance

### ISSUE THREAD

**Issue by ajh123** [miners-online/status#2]
**Additional context**

Scheduled downtime for the Minecraft server to start on 2024-09-05T20:20:00+0000 (ISO 8601 date) and end at 2024-09-06T12:00:00+0000 (ISO 8601 date) due to resource constraints.

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by ajh123** [comment]
Service will be down due to resource constraints.
